version: '3.4'

services:
  kevin.treminio.university.service:
    image: ${DOCKER_REGISTRY-}kevintreminiouniversityservice
    container_name: kevin.treminio.university.service
    build:
      context: .
      dockerfile: Backend/Domain/University/Kevin.Treminio.University.Service/Dockerfile
    ports:
      - "8082:80"
      - "8083:443"
    networks:
      - backend
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    volumes:
      - ./Backend/Infrastructure/Database/mssql:/var/opt/mssql/data
    ports:
      - "1433:1433"
    networks:
      - backend
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.2
    container_name: keycloak
    restart: on-failure
    command: ["start-dev"]
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mssql
      - KC_DB_URL=jdbc:sqlserver://sqlserver:1433;databaseName=keycloak;encrypt=false
      - KC_DB_USERNAME=sa
      - KC_DB_PASSWORD=Password123
      - KC_TRANSACTION_XA_ENABLED=false
    
    volumes:
      - ./idp/data:/opt/keycloak/data
    networks:
      - backend
networks:
  backend:
    name: backend
    driver: bridge
